module.exports = function (app) {
    app.use("/test/getTestContent",(req,res)=>{
        res.json(require("./json/test.json"))
    })
    app.use("/test/Mombaby",(req,res)=>{
        res.json(require("./json/Mombaby.json"))
    })
    app.use("/test/Beautiful",(req,res)=>{
        res.json(require("./json/Beautiful.json"))
    })
    app.use("/test/Clothes",(req,res)=>{
        res.json(require("./json/Clothes.json"))
    })
    app.use("/test/Foods",(req,res)=>{
        res.json(require("./json/Foods.json"))
    })
    app.use("/test/CarThings",(req,res)=>{
        res.json(require("./json/CarThings.json"))
    })
    app.use("/test/momImgLoading",(req,res)=>{
        res.json(require("./json/momImgLoading.json"))
    })
    app.use("/test/foodImgLoading",(req,res)=>{
        res.json(require("./json/foodImgLoad.json"))
    })
    app.use("/test/Search",(req,res)=>{
            res.json(require("./json/Search.json"))
        })
}